name: Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - run: "echo We're in ${{vars.ENVIRONMENT_NAME}}"
