name: Deploy
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  Deploy_prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - run: "echo We\\'re in ${{vars.ENVIRONMENT_NAME}}"

  Deploy_not:
    runs-on: ubuntu-latest
    steps:
      - run: "echo We\\'re not in an environment"
